import { Recipe } from '../types/recipe';

export const sampleRecipes: Recipe[] = [
  {
    id: '1',
    title: 'Classic Margherita Pizza',
    description: 'A simple and delicious Italian pizza with fresh mozzarella, tomatoes, and basil.',
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'medium',
    category: 'Italian',
    tags: ['vegetarian', 'italian', 'dinner'],
    ingredients: [
      { id: '1-1', name: 'Pizza dough', amount: 1, unit: 'ball' },
      { id: '1-2', name: 'San Marzano tomatoes', amount: 400, unit: 'g' },
      { id: '1-3', name: 'Fresh mozzarella', amount: 250, unit: 'g' },
      { id: '1-4', name: 'Fresh basil', amount: 10, unit: 'leaves' },
      { id: '1-5', name: 'Olive oil', amount: 2, unit: 'tbsp' },
      { id: '1-6', name: 'Salt', amount: 1, unit: 'tsp' },
    ],
    steps: [
      { id: '1-s1', order: 1, instruction: 'Preheat oven to 475°F (245°C). If using a pizza stone, place it in the oven.' },
      { id: '1-s2', order: 2, instruction: 'Roll out pizza dough on a floured surface to desired thickness.' },
      { id: '1-s3', order: 3, instruction: 'Crush tomatoes and spread evenly over dough, leaving a 1-inch border.' },
      { id: '1-s4', order: 4, instruction: 'Tear mozzarella and distribute over tomatoes. Drizzle with olive oil and sprinkle with salt.' },
      { id: '1-s5', order: 5, instruction: 'Bake for 12-15 minutes until crust is golden and cheese is bubbly.', duration: 15 },
      { id: '1-s6', order: 6, instruction: 'Remove from oven, top with fresh basil leaves, and serve immediately.' },
    ],
    rating: 4.8,
    reviews: [
      {
        id: 'r1-1',
        author: 'Maria',
        rating: 5,
        comment: 'Perfect! Just like in Naples!',
        createdAt: '2025-11-10T14:30:00Z',
      },
      {
        id: 'r1-2',
        author: 'John',
        rating: 4,
        comment: 'Great recipe, very authentic.',
        createdAt: '2025-11-12T18:20:00Z',
      },
    ],
    isFavorite: true,
    createdAt: '2025-11-01T10:00:00Z',
    updatedAt: '2025-11-01T10:00:00Z',
  },
  {
    id: '2',
    title: 'Thai Green Curry',
    description: 'Aromatic and creamy Thai curry with vegetables and coconut milk.',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: 'easy',
    category: 'Thai',
    tags: ['thai', 'curry', 'vegan', 'dinner'],
    ingredients: [
      { id: '2-1', name: 'Green curry paste', amount: 3, unit: 'tbsp' },
      { id: '2-2', name: 'Coconut milk', amount: 400, unit: 'ml' },
      { id: '2-3', name: 'Bell peppers', amount: 2, unit: 'whole' },
      { id: '2-4', name: 'Bamboo shoots', amount: 200, unit: 'g' },
      { id: '2-5', name: 'Thai basil', amount: 1, unit: 'bunch' },
      { id: '2-6', name: 'Lime', amount: 1, unit: 'whole' },
    ],
    steps: [
      { id: '2-s1', order: 1, instruction: 'Heat oil in a large pan and fry curry paste for 1-2 minutes until fragrant.', duration: 2 },
      { id: '2-s2', order: 2, instruction: 'Add coconut milk and bring to a simmer.' },
      { id: '2-s3', order: 3, instruction: 'Add vegetables and cook for 15-20 minutes until tender.', duration: 20 },
      { id: '2-s4', order: 4, instruction: 'Stir in Thai basil and lime juice, then serve over rice.' },
    ],
    rating: 4.6,
    reviews: [],
    isFavorite: false,
    createdAt: '2025-11-02T12:00:00Z',
    updatedAt: '2025-11-02T12:00:00Z',
  },
  {
    id: '3',
    title: 'Classic Chocolate Chip Cookies',
    description: 'Soft, chewy chocolate chip cookies that are perfect every time.',
    imageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800',
    prepTime: 15,
    cookTime: 12,
    servings: 24,
    difficulty: 'easy',
    category: 'Dessert',
    tags: ['dessert', 'baking', 'cookies', 'sweet'],
    ingredients: [
      { id: '3-1', name: 'All-purpose flour', amount: 280, unit: 'g' },
      { id: '3-2', name: 'Butter', amount: 225, unit: 'g' },
      { id: '3-3', name: 'Brown sugar', amount: 200, unit: 'g' },
      { id: '3-4', name: 'Granulated sugar', amount: 100, unit: 'g' },
      { id: '3-5', name: 'Eggs', amount: 2, unit: 'whole' },
      { id: '3-6', name: 'Vanilla extract', amount: 2, unit: 'tsp' },
      { id: '3-7', name: 'Baking soda', amount: 1, unit: 'tsp' },
      { id: '3-8', name: 'Salt', amount: 1, unit: 'tsp' },
      { id: '3-9', name: 'Chocolate chips', amount: 340, unit: 'g' },
    ],
    steps: [
      { id: '3-s1', order: 1, instruction: 'Preheat oven to 375°F (190°C).' },
      { id: '3-s2', order: 2, instruction: 'Cream together butter and sugars until light and fluffy.' },
      { id: '3-s3', order: 3, instruction: 'Beat in eggs and vanilla extract.' },
      { id: '3-s4', order: 4, instruction: 'Mix in flour, baking soda, and salt until just combined.' },
      { id: '3-s5', order: 5, instruction: 'Fold in chocolate chips.' },
      { id: '3-s6', order: 6, instruction: 'Drop rounded tablespoons of dough onto baking sheets.' },
      { id: '3-s7', order: 7, instruction: 'Bake for 10-12 minutes until edges are golden.', duration: 12 },
      { id: '3-s8', order: 8, instruction: 'Cool on baking sheet for 5 minutes before transferring to wire rack.', duration: 5 },
    ],
    rating: 5.0,
    reviews: [
      {
        id: 'r3-1',
        author: 'Sarah',
        rating: 5,
        comment: 'Best chocolate chip cookies I\'ve ever made!',
        createdAt: '2025-11-08T16:45:00Z',
      },
    ],
    isFavorite: true,
    createdAt: '2025-11-05T09:00:00Z',
    updatedAt: '2025-11-05T09:00:00Z',
  },
  {
    id: '4',
    title: 'Mediterranean Quinoa Salad',
    description: 'Fresh and healthy quinoa salad with Mediterranean flavors.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
    prepTime: 10,
    cookTime: 20,
    servings: 6,
    difficulty: 'easy',
    category: 'Salad',
    tags: ['healthy', 'vegetarian', 'mediterranean', 'lunch'],
    ingredients: [
      { id: '4-1', name: 'Quinoa', amount: 200, unit: 'g' },
      { id: '4-2', name: 'Cherry tomatoes', amount: 250, unit: 'g' },
      { id: '4-3', name: 'Cucumber', amount: 1, unit: 'whole' },
      { id: '4-4', name: 'Feta cheese', amount: 150, unit: 'g' },
      { id: '4-5', name: 'Kalamata olives', amount: 100, unit: 'g' },
      { id: '4-6', name: 'Red onion', amount: 0.5, unit: 'whole' },
      { id: '4-7', name: 'Lemon juice', amount: 3, unit: 'tbsp' },
      { id: '4-8', name: 'Olive oil', amount: 4, unit: 'tbsp' },
    ],
    steps: [
      { id: '4-s1', order: 1, instruction: 'Cook quinoa according to package directions, then let cool.', duration: 20 },
      { id: '4-s2', order: 2, instruction: 'Halve cherry tomatoes, dice cucumber, and thinly slice red onion.' },
      { id: '4-s3', order: 3, instruction: 'Combine all vegetables with cooled quinoa in a large bowl.' },
      { id: '4-s4', order: 4, instruction: 'Crumble feta and add olives to the bowl.' },
      { id: '4-s5', order: 5, instruction: 'Whisk together lemon juice and olive oil, then toss with salad.' },
      { id: '4-s6', order: 6, instruction: 'Season with salt and pepper, refrigerate for 30 minutes before serving.' },
    ],
    rating: 4.5,
    reviews: [],
    isFavorite: false,
    createdAt: '2025-11-07T11:30:00Z',
    updatedAt: '2025-11-07T11:30:00Z',
  },
  {
    id: '5',
    title: 'Beef Tacos',
    description: 'Flavorful ground beef tacos with all the fixings.',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'easy',
    category: 'Mexican',
    tags: ['mexican', 'dinner', 'beef', 'quick'],
    ingredients: [
      { id: '5-1', name: 'Ground beef', amount: 500, unit: 'g' },
      { id: '5-2', name: 'Taco seasoning', amount: 2, unit: 'tbsp' },
      { id: '5-3', name: 'Taco shells', amount: 8, unit: 'whole' },
      { id: '5-4', name: 'Lettuce', amount: 1, unit: 'head' },
      { id: '5-5', name: 'Tomatoes', amount: 2, unit: 'whole' },
      { id: '5-6', name: 'Cheddar cheese', amount: 200, unit: 'g' },
      { id: '5-7', name: 'Sour cream', amount: 150, unit: 'g' },
    ],
    steps: [
      { id: '5-s1', order: 1, instruction: 'Brown ground beef in a large skillet over medium-high heat.', duration: 8 },
      { id: '5-s2', order: 2, instruction: 'Drain excess fat and add taco seasoning with water. Simmer for 5 minutes.', duration: 5 },
      { id: '5-s3', order: 3, instruction: 'Warm taco shells according to package directions.' },
      { id: '5-s4', order: 4, instruction: 'Shred lettuce, dice tomatoes, and grate cheese.' },
      { id: '5-s5', order: 5, instruction: 'Assemble tacos with beef and desired toppings.' },
    ],
    rating: 4.7,
    reviews: [
      {
        id: 'r5-1',
        author: 'Carlos',
        rating: 5,
        comment: 'Simple and delicious!',
        createdAt: '2025-11-14T19:00:00Z',
      },
    ],
    isFavorite: true,
    createdAt: '2025-11-10T15:00:00Z',
    updatedAt: '2025-11-10T15:00:00Z',
  },
  {
    id: '6',
    title: 'French Onion Soup',
    description: 'Rich and comforting soup with caramelized onions and melted Gruyère.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
    prepTime: 15,
    cookTime: 60,
    servings: 4,
    difficulty: 'medium',
    category: 'French',
    tags: ['french', 'soup', 'comfort-food', 'dinner'],
    ingredients: [
      { id: '6-1', name: 'Yellow onions', amount: 6, unit: 'whole' },
      { id: '6-2', name: 'Butter', amount: 50, unit: 'g' },
      { id: '6-3', name: 'Beef broth', amount: 1.5, unit: 'L' },
      { id: '6-4', name: 'White wine', amount: 125, unit: 'ml' },
      { id: '6-5', name: 'Baguette', amount: 1, unit: 'whole' },
      { id: '6-6', name: 'Gruyère cheese', amount: 200, unit: 'g' },
      { id: '6-7', name: 'Thyme', amount: 2, unit: 'sprigs' },
    ],
    steps: [
      { id: '6-s1', order: 1, instruction: 'Thinly slice onions and caramelize in butter over medium-low heat for 40-45 minutes.', duration: 45 },
      { id: '6-s2', order: 2, instruction: 'Add wine and cook until evaporated, about 5 minutes.', duration: 5 },
      { id: '6-s3', order: 3, instruction: 'Add beef broth and thyme, simmer for 20 minutes.', duration: 20 },
      { id: '6-s4', order: 4, instruction: 'Slice baguette and toast until golden.' },
      { id: '6-s5', order: 5, instruction: 'Ladle soup into oven-safe bowls, top with bread and grated Gruyère.' },
      { id: '6-s6', order: 6, instruction: 'Broil until cheese is melted and bubbly, about 3-5 minutes.', duration: 5 },
    ],
    rating: 4.9,
    reviews: [],
    isFavorite: false,
    createdAt: '2025-11-03T13:00:00Z',
    updatedAt: '2025-11-03T13:00:00Z',
  },
];

export const categories = [
  'All',
  'Italian',
  'Thai',
  'Mexican',
  'French',
  'Dessert',
  'Salad',
  'Breakfast',
  'Lunch',
  'Dinner',
];

export const allTags = [
  'vegetarian',
  'vegan',
  'gluten-free',
  'dairy-free',
  'quick',
  'healthy',
  'comfort-food',
  'baking',
  'dessert',
  'italian',
  'thai',
  'mexican',
  'french',
  'mediterranean',
];
